actors:
  takky:
    image_url: /images/actors/takky.jpg
    name: takky
    url: /takky.html
  suzuki:
    image_url: /images/actors/suzuki.jpg
    name: suzuki
    url: /suzuki.html
  miyanoji:
    image_url: /images/actors/miyanoji.jpg
    name: miyanoji
    url: /miyanoji.html
  issie:
    image_url: /images/actors/issie.jpg
    name: issie
    url: /issie.html
  fukkun:
    image_url: /images/actors/guest.jpg
    name: fukkun
    url: #
  Guest:
    image_url: /images/actors/guest.jpg
    name: Guest
    url: #
author: system and genius
description: SIerが雑談するテック系ポッドキャストです。
description_long: SEの番組です。SIerが雑談するテック系ポッドキャストです。今興味を持っている技術・ガジェット、業界や技術的に悩んでいることなど、リスナーさんと共有できれば嬉しいです！
email: systemand.online@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: systemand
itunes_podcast_url: pcast://feeds.feedburner.com/sagonline
keywords: テック系,エンジニア,中堅,ポッドキャスト,Podcast
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: systemand.online
url: https://systemand.online
cdn: https://cdn.systemand.online
gems:
  - jekyll-sitemap
paginate: 10

